import { type PricingPlan } from '@/components/ui/pricing';

/**
 * TaxWiseIndia service pricing (46 services).
 * Price strings intentionally include '+ Govt. Fees*' on every plan as requested.
 * Important: government/statutory charges apply only where the service legally requires them; they are not charged for every service.
 * When Vakilsearch published a price/package, that amount is used as a competitor reference.
 * Where no fixed Vakilsearch fee was publicly verified, amounts are suggested TaxWiseIndia benchmark prices, NOT Vakilsearch quotes.
 * Confirm all fees, scope, taxes and statutory charges before publishing/accepting orders.
 */
export const SERVICE_PRICING: Record<string, PricingPlan[]> = {

  // Private Limited Company — Vakilsearch published package prices.
  'private-limited-company': [
    { name: "Starter", price: "999 + Govt. Fees*", period: "project", features: ["Company name approval support", "DSC for 2 directors", "MOA & AOA preparation", "Certificate of Incorporation", "PAN + TAN", "Status tracking", "Government / statutory fees extra where applicable*"], description: "Company incorporation with filing and post-registration support.", buttonText: "Get Started", href: "#", isPopular: false },
    { name: "Pro", price: "1499 + Govt. Fees*", period: "project", features: ["Everything in Starter", "Dedicated filing expert", "Compliance starter kit", "Priority support", "Compliance reminders and invoicing", "Government / statutory fees extra where applicable*"], description: "Company incorporation with filing and post-registration support.", buttonText: "Get Started", href: "#", isPopular: true },
    { name: "Enterprise", price: "3499 + Govt. Fees*", period: "project", features: ["Everything in Pro", "Priority filing support", "Trademark registration support", "MSME/Udyam registration support", "Business setup guidance", "Government / statutory fees extra where applicable*"], description: "Company incorporation with filing and post-registration support.", buttonText: "Contact Sales", href: "#", isPopular: false },
  ],

  // LLP Registration — Vakilsearch published package prices.
  'llp-registration': [
    { name: "Starter", price: "999 + Govt. Fees*", period: "project", features: ["Name reservation support", "LLP incorporation form filing", "LLP incorporation certificate", "LLP agreement filing", "PAN + TAN", "Government / statutory fees extra where applicable*"], description: "LLP formation with optional priority processing and first-year compliance support.", buttonText: "Get Started", href: "#", isPopular: false },
    { name: "Pro", price: "2499 + Govt. Fees*", period: "project", features: ["Everything in Starter", "Priority name reservation", "Expedited DSC processing", "Faster LLP agreement filing", "Government / statutory fees extra where applicable*"], description: "LLP formation with optional priority processing and first-year compliance support.", buttonText: "Get Started", href: "#", isPopular: true },
    { name: "Enterprise", price: "10999 + Govt. Fees*", period: "project", features: ["Everything in Pro", "Senior CA/CS strategy call", "Year-one Form 8 and Form 11 filing support", "DIR-3 KYC support for 2 partners", "Government / statutory fees extra where applicable*"], description: "LLP formation with optional priority processing and first-year compliance support.", buttonText: "Contact Sales", href: "#", isPopular: false },
  ],

  // OPC Registration — Vakilsearch published package prices; confirm individual package inclusions at checkout.
  'opc-registration': [
    { name: "Starter", price: "999 + Govt. Fees*", period: "project", features: ["Name approval support", "MOA & AOA", "Incorporation certificate", "PAN + TAN", "Government / statutory fees extra where applicable*"], description: "One Person Company registration for single founders, with optional additional setup support.", buttonText: "Get Started", href: "#", isPopular: false },
    { name: "Pro", price: "1499 + Govt. Fees*", period: "project", features: ["Everything in Starter", "Dedicated filing expert", "Compliance starter kit", "Priority support", "Government / statutory fees extra where applicable*"], description: "One Person Company registration for single founders, with optional additional setup support.", buttonText: "Get Started", href: "#", isPopular: true },
    { name: "Enterprise", price: "3499 + Govt. Fees*", period: "project", features: ["Everything in Pro", "Priority filing support", "MSME registration support", "Trademark/business setup support", "Government / statutory fees extra where applicable*"], description: "One Person Company registration for single founders, with optional additional setup support.", buttonText: "Contact Sales", href: "#", isPopular: false },
  ],

  // Partnership Firm — Vakilsearch published package prices.
  'partnership-firm': [
    { name: "Starter", price: "2499 + Govt. Fees*", period: "project", features: ["Expert-assisted process", "Partnership deed drafting", "Deed submission assistance", "Firm PAN support", "Government / statutory fees extra where applicable*"], description: "Partnership formation with optional GST, filing and accounting support.", buttonText: "Get Started", href: "#", isPopular: false },
    { name: "Pro", price: "4999 + Govt. Fees*", period: "project", features: ["Everything in Starter", "GST registration support", "GSTR-1 and GSTR-3B filing for 12 months (up to 300 transactions)", "One-year accounting software", "Government / statutory fees extra where applicable*"], description: "Partnership formation with optional GST, filing and accounting support.", buttonText: "Get Started", href: "#", isPopular: true },
    { name: "Enterprise", price: "8999 + Govt. Fees*", period: "project", features: ["Everything in Pro", "Dedicated account manager", "Trademark registration support", "One-year ITR filing support (published scope limit applies)", "Government / statutory fees extra where applicable*"], description: "Partnership formation with optional GST, filing and accounting support.", buttonText: "Contact Sales", href: "#", isPopular: false },
  ],

  // Sole Proprietorship — Vakilsearch published starting/package prices; starting offer may have conditions and applicable tax.
  'sole-proprietorship': [
    { name: "Starter", price: "499 + Govt. Fees*", period: "project", features: ["Expert-assisted documentation", "GST or Udyam/MSME registration support (scope-dependent)", "Basic registration guidance", "Government / statutory fees extra where applicable*"], description: "Registration and compliance support for sole proprietors. Starting offer and inclusions should be confirmed before purchase.", buttonText: "Get Started", href: "#", isPopular: false },
    { name: "Pro", price: "3499 + Govt. Fees*", period: "project", features: ["Everything in Starter", "GST registration support", "Udyam/MSME registration support", "GST filing for 12 months (up to 300 transactions)", "Government / statutory fees extra where applicable*"], description: "Registration and compliance support for sole proprietors. Starting offer and inclusions should be confirmed before purchase.", buttonText: "Get Started", href: "#", isPopular: true },
    { name: "Enterprise", price: "5999 + Govt. Fees*", period: "project", features: ["Everything in Pro", "GST filing for 12 months (up to 500 transactions)", "ITR filing support", "Expanded tax-compliance assistance", "Government / statutory fees extra where applicable*"], description: "Registration and compliance support for sole proprietors. Starting offer and inclusions should be confirmed before purchase.", buttonText: "Contact Sales", href: "#", isPopular: false },
  ],

  // Startup India — TaxWiseIndia suggested benchmark prices; Vakilsearch professional-assistance fee was not publicly fixed. DPIIT recognition itself is free.
  'startup-india': [
    { name: "Starter", price: "2999 + Govt. Fees*", period: "project", features: ["DPIIT recognition eligibility check", "Document checklist", "Application preparation support", "Application status guidance", "Government / statutory fees extra where applicable*"], description: "DPIIT recognition support, including eligibility review, document preparation and application follow-up. The government recognition application itself is free.", buttonText: "Get Started", href: "#", isPopular: false },
    { name: "Pro", price: "5999 + Govt. Fees*", period: "project", features: ["Everything in Starter", "Expanded application/document review", "Startup scheme and benefit guidance", "Recognition follow-up", "Government / statutory fees extra where applicable*"], description: "DPIIT recognition support, including eligibility review, document preparation and application follow-up. The government recognition application itself is free.", buttonText: "Get Started", href: "#", isPopular: true },
    { name: "Enterprise", price: "9999 + Govt. Fees*", period: "project", features: ["Everything in Pro", "Tax-benefit application guidance", "IPR benefit guidance", "Startup compliance consultation", "Government / statutory fees extra where applicable*"], description: "DPIIT recognition support, including eligibility review, document preparation and application follow-up. The government recognition application itself is free.", buttonText: "Contact Sales", href: "#", isPopular: false },
  ],

  // Section 8 Company — Vakilsearch published package prices; confirm exact package scope and statutory charges.
  'section-8-company': [
    { name: "Starter", price: "999 + Govt. Fees*", period: "project", features: ["Initial consultation", "Name reservation support", "NGO incorporation checklist", "Government / statutory fees extra where applicable*"], description: "Section 8 non-profit company incorporation with optional NGO compliance support.", buttonText: "Get Started", href: "#", isPopular: false },
    { name: "Pro", price: "2999 + Govt. Fees*", period: "project", features: ["Everything in Starter", "Section 8 company formation guidance", "Documentation and filing assistance", "Incorporation follow-up", "Government / statutory fees extra where applicable*"], description: "Section 8 non-profit company incorporation with optional NGO compliance support.", buttonText: "Get Started", href: "#", isPopular: true },
    { name: "Enterprise", price: "14999 + Govt. Fees*", period: "project", features: ["Everything in Pro", "Expanded NGO compliance support", "12A/80G application guidance", "FCRA-readiness guidance where eligible", "Government / statutory fees extra where applicable*"], description: "Section 8 non-profit company incorporation with optional NGO compliance support.", buttonText: "Contact Sales", href: "#", isPopular: false },
  ],

  // GST Registration — Vakilsearch published package prices; applicable taxes and any stamp-paper charges may be extra.
  'gst-registration': [
    { name: "Starter", price: "399 + Govt. Fees*", period: "project", features: ["GST application filing support", "Documentation checklist", "ARN/status tracking", "GST registration certificate support", "Government / statutory fees extra where applicable*"], description: "GST registration support from application filing to certificate follow-up. Approval remains subject to GST authority verification.", buttonText: "Get Started", href: "#", isPopular: false },
    { name: "Pro", price: "1999 + Govt. Fees*", period: "project", features: ["Everything in Starter", "Priority filing support", "Eligible Rule 14A workflow", "MSME registration support", "Compliance checklist and GST expert support", "Government / statutory fees extra where applicable*"], description: "GST registration support from application filing to certificate follow-up. Approval remains subject to GST authority verification.", buttonText: "Get Started", href: "#", isPopular: true },
    { name: "Enterprise", price: "3499 + Govt. Fees*", period: "project", features: ["Everything in Pro", "GST registration and Udyam support", "GST filing for 12 months within published transaction/turnover limits", "Compliance review", "Government / statutory fees extra where applicable*"], description: "GST registration support from application filing to certificate follow-up. Approval remains subject to GST authority verification.", buttonText: "Contact Sales", href: "#", isPopular: false },
  ],

  // GST Return Filing — Vakilsearch published package prices; page states taxes are additional.
  'gst-return-filing': [
    { name: "Starter", price: "999 + Govt. Fees*", period: "quarter", features: ["Expert-assisted GSTR-1 and GSTR-3B filing", "Three-month filing period", "Starter scope is for nil transactions", "Government / statutory fees extra where applicable*"], description: "Recurring GST return filing. Package scope depends on filing period, transactions and turnover limits.", buttonText: "Get Started", href: "#", isPopular: false },
    { name: "Pro", price: "2999 + Govt. Fees*", period: "year", features: ["GSTR-1 and GSTR-3B for 12 months", "GST registration included where stated", "Up to published transaction/turnover limit", "Government / statutory fees extra where applicable*"], description: "Recurring GST return filing. Package scope depends on filing period, transactions and turnover limits.", buttonText: "Get Started", href: "#", isPopular: true },
    { name: "Enterprise", price: "4999 + Govt. Fees*", period: "year", features: ["GSTR-1 and GSTR-3B for 12 months", "Higher published transaction/turnover limit", "One financial year of ITR filing within published scope", "Government / statutory fees extra where applicable*"], description: "Recurring GST return filing. Package scope depends on filing period, transactions and turnover limits.", buttonText: "Contact Sales", href: "#", isPopular: false },
  ],

  // Income Tax Filing — ₹2,499 starting professional fee is published by Vakilsearch; higher tiers are TaxWiseIndia benchmark suggestions, not verified Vakilsearch package prices.
  'income-tax-filing': [
    { name: "Starter", price: "2499 + Govt. Fees*", period: "project", features: ["Expert-assisted ITR filing", "Salaried / standard individual return support", "CA assistance", "Government / statutory fees extra where applicable*"], description: "CA-assisted income tax return filing. Complex business income, audit work, notices or advanced tax planning may require a separate quote.", buttonText: "Get Started", href: "#", isPopular: false },
    { name: "Pro", price: "4999 + Govt. Fees*", period: "project", features: ["Higher-complexity individual or business return filing", "Business/profession income support", "Additional schedules and document review", "Government / statutory fees extra where applicable*"], description: "CA-assisted income tax return filing. Complex business income, audit work, notices or advanced tax planning may require a separate quote.", buttonText: "Get Started", href: "#", isPopular: true },
    { name: "Enterprise", price: "14999 + Govt. Fees*", period: "project", features: ["Company and corporate income tax return support", "Company ITR support", "Audit/tax-planning coordination where separately agreed", "Government / statutory fees extra where applicable*"], description: "CA-assisted income tax return filing. Complex business income, audit work, notices or advanced tax planning may require a separate quote.", buttonText: "Contact Sales", href: "#", isPopular: false },
  ],

  // TDS Return Filing — TaxWiseIndia suggested benchmark prices; Vakilsearch service page describes filing support but no fixed public professional fee was verified.
  'tds-return-filing': [
    { name: "Starter", price: "1499 + Govt. Fees*", period: "quarter", features: ["Quarterly TDS return preparation and filing", "Challan/document review", "Basic filing support", "Government / statutory fees extra where applicable*"], description: "Quarterly TDS return preparation, submission and compliance assistance. Final scope depends on deductee volume, corrections and filing period.", buttonText: "Get Started", href: "#", isPopular: false },
    { name: "Pro", price: "3499 + Govt. Fees*", period: "quarter", features: ["Everything in Starter", "Higher deductee-volume allowance", "Form 16/16A support where applicable", "Revision support", "Government / statutory fees extra where applicable*"], description: "Quarterly TDS return preparation, submission and compliance assistance. Final scope depends on deductee volume, corrections and filing period.", buttonText: "Get Started", href: "#", isPopular: true },
    { name: "Enterprise", price: "7999 + Govt. Fees*", period: "quarter", features: ["Everything in Pro", "High-volume deductee support", "TDS discrepancy follow-up", "Dedicated compliance support", "Government / statutory fees extra where applicable*"], description: "Quarterly TDS return preparation, submission and compliance assistance. Final scope depends on deductee volume, corrections and filing period.", buttonText: "Contact Sales", href: "#", isPopular: false },
  ],

  // GST LUT — TaxWiseIndia suggested benchmark prices; Vakilsearch page did not publish a fixed professional fee.
  'gst-lut': [
    { name: "Starter", price: "1999 + Govt. Fees*", period: "project", features: ["LUT eligibility/document checklist", "Form RFD-11 preparation", "GST portal filing assistance", "Government / statutory fees extra where applicable*"], description: "Letter of Undertaking (LUT) filing support for eligible exporters, including RFD-11 preparation, portal filing and acknowledgement follow-up.", buttonText: "Get Started", href: "#", isPopular: false },
    { name: "Pro", price: "3999 + Govt. Fees*", period: "project", features: ["Everything in Starter", "Acknowledgement and status follow-up", "Expert consultation", "Government / statutory fees extra where applicable*"], description: "Letter of Undertaking (LUT) filing support for eligible exporters, including RFD-11 preparation, portal filing and acknowledgement follow-up.", buttonText: "Get Started", href: "#", isPopular: true },
    { name: "Enterprise", price: "6999 + Govt. Fees*", period: "project", features: ["Everything in Pro", "Renewal reminder/support", "Export compliance consultation", "Dedicated follow-up", "Government / statutory fees extra where applicable*"], description: "Letter of Undertaking (LUT) filing support for eligible exporters, including RFD-11 preparation, portal filing and acknowledgement follow-up.", buttonText: "Contact Sales", href: "#", isPopular: false },
  ],

  // GST Cancellation — TaxWiseIndia suggested benchmark prices; no fixed Vakilsearch professional fee was verified.
  'gst-cancellation': [
    { name: "Starter", price: "2999 + Govt. Fees*", period: "project", features: ["Eligibility and document check", "Cancellation application preparation", "Portal filing/status follow-up", "Government / statutory fees extra where applicable*"], description: "GST cancellation application and closure support. Pending returns, ITC reversals or notices may change scope and cost.", buttonText: "Get Started", href: "#", isPopular: false },
    { name: "Pro", price: "5999 + Govt. Fees*", period: "project", features: ["Everything in Starter", "Pending return checklist", "Final-return guidance where applicable", "Priority support", "Government / statutory fees extra where applicable*"], description: "GST cancellation application and closure support. Pending returns, ITC reversals or notices may change scope and cost.", buttonText: "Get Started", href: "#", isPopular: true },
    { name: "Enterprise", price: "11999 + Govt. Fees*", period: "project", features: ["Everything in Pro", "Complex cancellation case review", "Notice/ITC issue coordination", "Dedicated expert support", "Government / statutory fees extra where applicable*"], description: "GST cancellation application and closure support. Pending returns, ITC reversals or notices may change scope and cost.", buttonText: "Contact Sales", href: "#", isPopular: false },
  ],

  // Tax Advisory — TaxWiseIndia suggested benchmark prices; Vakilsearch did not publish a fixed tax-advisory package price.
  'tax-advisory': [
    { name: "Starter", price: "1499 + Govt. Fees*", period: "project", features: ["Focused tax consultation", "Basic query review", "Action-point summary", "Government / statutory fees extra where applicable*"], description: "Tax consultation and planning support, with the scope tailored to the transaction, tax issue and required support frequency.", buttonText: "Get Started", href: "#", isPopular: false },
    { name: "Pro", price: "4999 + Govt. Fees*", period: "project", features: ["Everything in Starter", "Written advisory note", "Tax-planning review", "Follow-up session", "Government / statutory fees extra where applicable*"], description: "Tax consultation and planning support, with the scope tailored to the transaction, tax issue and required support frequency.", buttonText: "Get Started", href: "#", isPopular: true },
    { name: "Enterprise", price: "14999 + Govt. Fees*", period: "month", features: ["Monthly advisory retainer", "Transaction/tax-structure review", "Ongoing tax query support", "Dedicated advisor subject to scope", "Government / statutory fees extra where applicable*"], description: "Tax consultation and planning support, with the scope tailored to the transaction, tax issue and required support frequency.", buttonText: "Contact Sales", href: "#", isPopular: false },
  ],

  // ROC Annual Filing — Published Vakilsearch annual-compliance package prices used as the closest matching service; government filing fees billed extra.
  'roc-annual-filing': [
    { name: "Starter", price: "6988 + Govt. Fees*", period: "year", features: ["AOC-4 and MGT-7 annual filing support", "Auditor appointment filing support", "DIR-3 KYC for up to 2 directors", "Board/AGM documentation", "Government / statutory fees extra where applicable*"], description: "Annual MCA/ROC filing and corporate compliance support. Government filing fees and statutory charges are extra.", buttonText: "Get Started", href: "#", isPopular: false },
    { name: "Pro", price: "11988 + Govt. Fees*", period: "year", features: ["Everything in Starter", "Bookkeeping up to published annual transaction limit", "Ledger/journal maintenance", "Bank reconciliation and financial statements", "Government / statutory fees extra where applicable*"], description: "Annual MCA/ROC filing and corporate compliance support. Government filing fees and statutory charges are extra.", buttonText: "Get Started", href: "#", isPopular: true },
    { name: "Enterprise", price: "15588 + Govt. Fees*", period: "year", features: ["Everything in Pro", "GSTR-1/3B filing support", "GST reconciliation and monitoring", "Dedicated account manager/dashboard", "Government / statutory fees extra where applicable*"], description: "Annual MCA/ROC filing and corporate compliance support. Government filing fees and statutory charges are extra.", buttonText: "Contact Sales", href: "#", isPopular: false },
  ],

  // Company Compliance — Vakilsearch published annual-compliance prices; government filing fees are additional.
  'company-compliance': [
    { name: "Starter", price: "6988 + Govt. Fees*", period: "year", features: ["MCA/ROC annual filings", "Auditor appointment support", "DIR-3 KYC for up to 2 directors", "Board/AGM documents and statutory registers", "Government / statutory fees extra where applicable*"], description: "Annual corporate compliance with optional bookkeeping and GST support. Statutory filing fees are charged at actuals.", buttonText: "Get Started", href: "#", isPopular: false },
    { name: "Pro", price: "11988 + Govt. Fees*", period: "year", features: ["Everything in Starter", "Bookkeeping within published transaction/turnover limits", "Ledger/journal maintenance", "Bank reconciliation and financial statements", "Government / statutory fees extra where applicable*"], description: "Annual corporate compliance with optional bookkeeping and GST support. Statutory filing fees are charged at actuals.", buttonText: "Get Started", href: "#", isPopular: true },
    { name: "Enterprise", price: "15588 + Govt. Fees*", period: "year", features: ["Everything in Pro", "GST return support and reconciliation", "Ongoing GST monitoring/advisory", "Dedicated account manager and dashboard", "Government / statutory fees extra where applicable*"], description: "Annual corporate compliance with optional bookkeeping and GST support. Statutory filing fees are charged at actuals.", buttonText: "Contact Sales", href: "#", isPopular: false },
  ],

  // Director KYC — TaxWiseIndia suggested benchmark prices; Vakilsearch professional fee not publicly listed. Government KYC filing is free when filed by due date; late penalty is separate.
  'director-kyc': [
    { name: "Starter", price: "999 + Govt. Fees*", period: "project", features: ["DIR-3 KYC document checklist", "Form validation support", "Electronic submission and acknowledgement", "Government / statutory fees extra where applicable*"], description: "DIR-3 KYC preparation and filing support. Statutory penalties, if any, are separate and are not included in the professional fee.", buttonText: "Get Started", href: "#", isPopular: false },
    { name: "Pro", price: "1999 + Govt. Fees*", period: "project", features: ["Everything in Starter", "Additional director support (defined scope)", "DSC/update assistance where applicable", "Government / statutory fees extra where applicable*"], description: "DIR-3 KYC preparation and filing support. Statutory penalties, if any, are separate and are not included in the professional fee.", buttonText: "Get Started", href: "#", isPopular: true },
    { name: "Enterprise", price: "3999 + Govt. Fees*", period: "project", features: ["Everything in Pro", "Multiple-director case coordination", "Late-filing/notice assistance quoted by complexity", "Government / statutory fees extra where applicable*"], description: "DIR-3 KYC preparation and filing support. Statutory penalties, if any, are separate and are not included in the professional fee.", buttonText: "Contact Sales", href: "#", isPopular: false },
  ],

  // Company Changes — TaxWiseIndia suggested benchmark prices; Vakilsearch quotes vary by the type of corporate change.
  'company-changes': [
    { name: "Starter", price: "2999 + Govt. Fees*", period: "project", features: ["Resolution and document checklist", "Basic MCA/ROC change filing support", "Status tracking", "Government / statutory fees extra where applicable*"], description: "Corporate changes such as directors, name, authorised capital or business objects. Government filing/stamp fees depend on the change.", buttonText: "Get Started", href: "#", isPopular: false },
    { name: "Pro", price: "5999 + Govt. Fees*", period: "project", features: ["Everything in Starter", "Director appointment/removal filing support", "Form DIR-12 support where applicable", "Priority coordination", "Government / statutory fees extra where applicable*"], description: "Corporate changes such as directors, name, authorised capital or business objects. Government filing/stamp fees depend on the change.", buttonText: "Get Started", href: "#", isPopular: true },
    { name: "Enterprise", price: "11999 + Govt. Fees*", period: "project", features: ["Everything in Pro", "Capital/objects/MOA-AOA change coordination", "Complex change documentation", "Dedicated compliance expert", "Government / statutory fees extra where applicable*"], description: "Corporate changes such as directors, name, authorised capital or business objects. Government filing/stamp fees depend on the change.", buttonText: "Contact Sales", href: "#", isPopular: false },
  ],

  // Registered Office Change — TaxWiseIndia suggested benchmark prices; Vakilsearch page did not publish a fixed professional price.
  'registered-office-change': [
    { name: "Starter", price: "2499 + Govt. Fees*", period: "project", features: ["Local-limit address change checklist", "INC-22/document preparation support", "Filing status updates", "Government / statutory fees extra where applicable*"], description: "Registered-office change filing support. Government, publication and stamp charges depend on the jurisdiction and type of move.", buttonText: "Get Started", href: "#", isPopular: false },
    { name: "Pro", price: "6999 + Govt. Fees*", period: "project", features: ["Everything in Starter", "Within-state address change guidance", "Board/shareholder documentation as required", "Priority support", "Government / statutory fees extra where applicable*"], description: "Registered-office change filing support. Government, publication and stamp charges depend on the jurisdiction and type of move.", buttonText: "Get Started", href: "#", isPopular: true },
    { name: "Enterprise", price: "14999 + Govt. Fees*", period: "project", features: ["Everything in Pro", "Inter-state shift coordination where applicable", "Regional Director process support where required", "Dedicated compliance expert", "Government / statutory fees extra where applicable*"], description: "Registered-office change filing support. Government, publication and stamp charges depend on the jurisdiction and type of move.", buttonText: "Contact Sales", href: "#", isPopular: false },
  ],

  // Share Transfer — TaxWiseIndia suggested benchmark prices; Vakilsearch publishes a ₹999 consultation, not a fixed full-service transfer price.
  'share-transfer': [
    { name: "Starter", price: "3499 + Govt. Fees*", period: "project", features: ["Share-transfer document checklist", "SH-4 execution guidance", "Basic filing/transfer coordination", "Government / statutory fees extra where applicable*"], description: "Share-transfer documentation and process support. Stamp duty, valuation and foreign-remittance requirements may be additional.", buttonText: "Get Started", href: "#", isPopular: false },
    { name: "Pro", price: "7999 + Govt. Fees*", period: "project", features: ["Everything in Starter", "Valuation/stamp-duty coordination where needed", "Priority support", "Document verification", "Government / statutory fees extra where applicable*"], description: "Share-transfer documentation and process support. Stamp duty, valuation and foreign-remittance requirements may be additional.", buttonText: "Get Started", href: "#", isPopular: true },
    { name: "Enterprise", price: "15999 + Govt. Fees*", period: "project", features: ["Everything in Pro", "Complex/cross-border transfer coordination", "FEMA reporting guidance where applicable", "Dedicated company-secretarial support", "Government / statutory fees extra where applicable*"], description: "Share-transfer documentation and process support. Stamp duty, valuation and foreign-remittance requirements may be additional.", buttonText: "Contact Sales", href: "#", isPopular: false },
  ],

  // Company Closure — TaxWiseIndia suggested professional-service benchmark prices; Vakilsearch publishes an indicative total strike-off estimate, not a fixed checkout quote.
  'company-closure': [
    { name: "Starter", price: "4999 + Govt. Fees*", period: "project", features: ["Closure eligibility review", "STK-2/document checklist", "Affidavit and indemnity drafting support", "Government / statutory fees extra where applicable*"], description: "Company strike-off or closure support. The professional fee and government charges depend on pending filings, liabilities and whether winding-up is required.", buttonText: "Get Started", href: "#", isPopular: false },
    { name: "Pro", price: "9999 + Govt. Fees*", period: "project", features: ["Everything in Starter", "Pending ROC filing coordination", "Account/record closure checklist", "Priority follow-up", "Government / statutory fees extra where applicable*"], description: "Company strike-off or closure support. The professional fee and government charges depend on pending filings, liabilities and whether winding-up is required.", buttonText: "Get Started", href: "#", isPopular: true },
    { name: "Enterprise", price: "19999 + Govt. Fees*", period: "project", features: ["Everything in Pro", "Complex closure/winding-up consultation", "Creditor/liquidator coordination where required", "Dedicated legal/compliance expert", "Government / statutory fees extra where applicable*"], description: "Company strike-off or closure support. The professional fee and government charges depend on pending filings, liabilities and whether winding-up is required.", buttonText: "Contact Sales", href: "#", isPopular: false },
  ],

  // Trademark Registration — Vakilsearch publishes ₹1,499 Standard and ₹1,999 Express professional fees; higher tier is a TaxWiseIndia benchmark suggestion. Government filing fees are extra per class.
  'trademark-registration': [
    { name: "Starter", price: "1499 + Govt. Fees*", period: "project", features: ["Trademark search and application support", "Class selection guidance", "Application filing and tracking", "Government / statutory fees extra where applicable*"], description: "Trademark availability review and filing. Government fee is generally ₹4,500 per class for eligible individuals/startups/small enterprises or ₹9,000 for other applicants, plus applicable tax on professional fees.", buttonText: "Get Started", href: "#", isPopular: false },
    { name: "Pro", price: "1999 + Govt. Fees*", period: "project", features: ["Everything in Starter", "Express filing support where available", "Enhanced document review", "Government / statutory fees extra where applicable*"], description: "Trademark availability review and filing. Government fee is generally ₹4,500 per class for eligible individuals/startups/small enterprises or ₹9,000 for other applicants, plus applicable tax on professional fees.", buttonText: "Get Started", href: "#", isPopular: true },
    { name: "Enterprise", price: "4999 + Govt. Fees*", period: "project", features: ["Everything in Pro", "Expanded brand advisory", "Objection-response preparation allowance subject to scope", "Dedicated IP support", "Government / statutory fees extra where applicable*"], description: "Trademark availability review and filing. Government fee is generally ₹4,500 per class for eligible individuals/startups/small enterprises or ₹9,000 for other applicants, plus applicable tax on professional fees.", buttonText: "Contact Sales", href: "#", isPopular: false },
  ],

  // Trademark Search — TaxWiseIndia suggested benchmark prices; a free public-register search is available, but standalone Vakilsearch assisted package prices were not verified.
  'trademark-search': [
    { name: "Starter", price: "499 + Govt. Fees*", period: "project", features: ["Basic wordmark search", "Preliminary availability check", "Summary of obvious matches", "Government / statutory fees extra where applicable*"], description: "Trademark search and preliminary risk review before filing. The statutory filing fee is separate if you proceed to registration.", buttonText: "Get Started", href: "#", isPopular: false },
    { name: "Pro", price: "1499 + Govt. Fees*", period: "project", features: ["Everything in Starter", "Phonetic and similar-name review", "Logo/device search where requested", "Government / statutory fees extra where applicable*"], description: "Trademark search and preliminary risk review before filing. The statutory filing fee is separate if you proceed to registration.", buttonText: "Get Started", href: "#", isPopular: true },
    { name: "Enterprise", price: "3999 + Govt. Fees*", period: "project", features: ["Everything in Pro", "Expanded risk review", "Class/brand strategy discussion", "Written search report", "Government / statutory fees extra where applicable*"], description: "Trademark search and preliminary risk review before filing. The statutory filing fee is separate if you proceed to registration.", buttonText: "Contact Sales", href: "#", isPopular: false },
  ],

  // Trademark Renewal — TaxWiseIndia suggested professional-service prices; Vakilsearch page does not publish a fixed professional package fee. Government renewal e-filing fee is typically ₹9,000 per class.
  'trademark-renewal': [
    { name: "Starter", price: "2499 + Govt. Fees*", period: "project", features: ["TM-R renewal application preparation", "Registration detail/document check", "Filing status follow-up", "Government / statutory fees extra where applicable*"], description: "Trademark renewal and status support. Government renewal fees and late/restoration charges are additional per class where applicable.", buttonText: "Get Started", href: "#", isPopular: false },
    { name: "Pro", price: "5999 + Govt. Fees*", period: "project", features: ["Everything in Starter", "Expiry/grace-period review", "Restoration guidance if eligible", "Government / statutory fees extra where applicable*"], description: "Trademark renewal and status support. Government renewal fees and late/restoration charges are additional per class where applicable.", buttonText: "Get Started", href: "#", isPopular: true },
    { name: "Enterprise", price: "9999 + Govt. Fees*", period: "project", features: ["Everything in Pro", "Notice/correction coordination", "Multiple-class coordination", "Dedicated IP support", "Government / statutory fees extra where applicable*"], description: "Trademark renewal and status support. Government renewal fees and late/restoration charges are additional per class where applicable.", buttonText: "Contact Sales", href: "#", isPopular: false },
  ],

  // Trademark Objection — TaxWiseIndia suggested benchmark prices; no fixed Vakilsearch package fee was verified. Published guidance gives broad market ranges for objection response and hearings.
  'trademark-objection': [
    { name: "Starter", price: "2999 + Govt. Fees*", period: "project", features: ["Examination report review", "Draft reply preparation", "Basic document checklist", "Government / statutory fees extra where applicable*"], description: "Trademark objection analysis and response preparation. Hearings, additional evidence and representation may require an expanded quote.", buttonText: "Get Started", href: "#", isPopular: false },
    { name: "Pro", price: "6999 + Govt. Fees*", period: "project", features: ["Everything in Starter", "Custom legal arguments", "Evidence/affidavit preparation support", "Priority review", "Government / statutory fees extra where applicable*"], description: "Trademark objection analysis and response preparation. Hearings, additional evidence and representation may require an expanded quote.", buttonText: "Get Started", href: "#", isPopular: true },
    { name: "Enterprise", price: "12999 + Govt. Fees*", period: "project", features: ["Everything in Pro", "Hearing preparation/representation subject to scope", "Additional evidence and filing coordination", "Dedicated IP lawyer", "Government / statutory fees extra where applicable*"], description: "Trademark objection analysis and response preparation. Hearings, additional evidence and representation may require an expanded quote.", buttonText: "Contact Sales", href: "#", isPopular: false },
  ],

  // Trademark Rectification — TaxWiseIndia suggested benchmark prices; Vakilsearch public fixed professional price was not verified. Government rectification/opposition filing fees may apply.
  'trademark-rectification': [
    { name: "Starter", price: "4999 + Govt. Fees*", period: "project", features: ["Initial rectification assessment", "Notice/application drafting support", "Basic consultation", "Government / statutory fees extra where applicable*"], description: "Trademark register correction, rectification or cancellation support. Government filing fees vary by proceeding and class.", buttonText: "Get Started", href: "#", isPopular: false },
    { name: "Pro", price: "9999 + Govt. Fees*", period: "project", features: ["Everything in Starter", "Evidence preparation", "Filing coordination", "Priority support", "Government / statutory fees extra where applicable*"], description: "Trademark register correction, rectification or cancellation support. Government filing fees vary by proceeding and class.", buttonText: "Get Started", href: "#", isPopular: true },
    { name: "Enterprise", price: "19999 + Govt. Fees*", period: "project", features: ["Everything in Pro", "Hearing/contested proceeding coordination", "Counter-statement support where needed", "Dedicated IP counsel", "Government / statutory fees extra where applicable*"], description: "Trademark register correction, rectification or cancellation support. Government filing fees vary by proceeding and class.", buttonText: "Contact Sales", href: "#", isPopular: false },
  ],

  // Copyright Registration — Vakilsearch location-specific page advertises copyright filing from ₹2,999 + government fees; higher tiers are TaxWiseIndia benchmark suggestions.
  'copyright-registration': [
    { name: "Starter", price: "2999 + Govt. Fees*", period: "project", features: ["Application preparation and filing support", "Work/document verification", "Basic status tracking", "Government / statutory fees extra where applicable*"], description: "Copyright application support for eligible creative works, software and related content. Government fee depends on the type of work; professional fees are additional.", buttonText: "Get Started", href: "#", isPopular: false },
    { name: "Pro", price: "6999 + Govt. Fees*", period: "project", features: ["Everything in Starter", "NOC/authorisation document support", "Software/code or complex-work documentation", "Priority support", "Government / statutory fees extra where applicable*"], description: "Copyright application support for eligible creative works, software and related content. Government fee depends on the type of work; professional fees are additional.", buttonText: "Get Started", href: "#", isPopular: true },
    { name: "Enterprise", price: "12999 + Govt. Fees*", period: "project", features: ["Everything in Pro", "Objection-response coordination", "Hearing/document follow-up where required", "Dedicated IP support", "Government / statutory fees extra where applicable*"], description: "Copyright application support for eligible creative works, software and related content. Government fee depends on the type of work; professional fees are additional.", buttonText: "Contact Sales", href: "#", isPopular: false },
  ],

  // Patent Registration — Vakilsearch publishes a ₹499 consultation and package starting points around ₹9,999/₹15,999; confirm the exact filing scope. Government patent fees are extra.
  'patent-registration': [
    { name: "Starter", price: "499 + Govt. Fees*", period: "project", features: ["Initial patent consultation only", "High-level process/eligibility discussion", "Not a full patent filing package", "Government / statutory fees extra where applicable*"], description: "Patent consultation and filing support. The ₹499 option is consultation-only; filing, examination and other statutory fees are separate.", buttonText: "Get Started", href: "#", isPopular: false },
    { name: "Pro", price: "9999 + Govt. Fees*", period: "project", features: ["Patentability/basic prior-art search support", "Provisional application drafting/filing support", "Document checklist", "Government / statutory fees extra where applicable*"], description: "Patent consultation and filing support. The ₹499 option is consultation-only; filing, examination and other statutory fees are separate.", buttonText: "Get Started", href: "#", isPopular: true },
    { name: "Enterprise", price: "15999 + Govt. Fees*", period: "project", features: ["Everything in Pro", "Complete specification support subject to scope", "Filing and prosecution coordination", "Dedicated patent professional", "Government / statutory fees extra where applicable*"], description: "Patent consultation and filing support. The ₹499 option is consultation-only; filing, examination and other statutory fees are separate.", buttonText: "Contact Sales", href: "#", isPopular: false },
  ],

  // MSME / Udyam — TaxWiseIndia suggested professional-service prices; Udyam registration on the government portal is free, and Vakilsearch assisted-service fee was not publicly verified.
  'msme-udyam': [
    { name: "Starter", price: "499 + Govt. Fees*", period: "project", features: ["Udyam registration assistance", "Document/data verification", "Certificate follow-up", "Government / statutory fees extra where applicable*"], description: "Assisted Udyam registration and MSME benefit guidance. Government registration itself is free; optional consulting/support fees are separate.", buttonText: "Get Started", href: "#", isPopular: false },
    { name: "Pro", price: "1499 + Govt. Fees*", period: "project", features: ["Everything in Starter", "NIC-code and enterprise-detail update support", "Priority document review", "Government / statutory fees extra where applicable*"], description: "Assisted Udyam registration and MSME benefit guidance. Government registration itself is free; optional consulting/support fees are separate.", buttonText: "Get Started", href: "#", isPopular: true },
    { name: "Enterprise", price: "2999 + Govt. Fees*", period: "project", features: ["Everything in Pro", "MSME scheme/subsidy guidance", "Tender-readiness checklist", "Dedicated expert consultation", "Government / statutory fees extra where applicable*"], description: "Assisted Udyam registration and MSME benefit guidance. Government registration itself is free; optional consulting/support fees are separate.", buttonText: "Contact Sales", href: "#", isPopular: false },
  ],

  // FSSAI Registration — Vakilsearch published package prices; government licence fees and applicable tax should be confirmed at checkout.
  'fssai': [
    { name: "Starter", price: "799 + Govt. Fees*", period: "project", features: ["Basic FSSAI registration assistance", "Document preparation", "Application tracking", "Government / statutory fees extra where applicable*"], description: "FSSAI registration/licensing help based on business type and eligibility. Government licence fees depend on category and validity.", buttonText: "Get Started", href: "#", isPopular: false },
    { name: "Pro", price: "2499 + Govt. Fees*", period: "project", features: ["State-level licence support", "Eligibility/document review", "Annual return support where included", "Government / statutory fees extra where applicable*"], description: "FSSAI registration/licensing help based on business type and eligibility. Government licence fees depend on category and validity.", buttonText: "Get Started", href: "#", isPopular: true },
    { name: "Enterprise", price: "4499 + Govt. Fees*", period: "project", features: ["Central licence support", "Import/export food compliance guidance", "Dedicated manager support", "Government / statutory fees extra where applicable*"], description: "FSSAI registration/licensing help based on business type and eligibility. Government licence fees depend on category and validity.", buttonText: "Contact Sales", href: "#", isPopular: false },
  ],

  // Import Export Code (IEC) — TaxWiseIndia suggested benchmark prices; current fixed Vakilsearch web price was not verified. Government/portal charges, if any, are additional.
  'iec': [
    { name: "Starter", price: "1499 + Govt. Fees*", period: "project", features: ["IEC application assistance", "Document verification", "Online filing/status follow-up", "Government / statutory fees extra where applicable*"], description: "Importer Exporter Code application and related export setup support. Final costs depend on the scope and current DGFT requirements.", buttonText: "Get Started", href: "#", isPopular: false },
    { name: "Pro", price: "3499 + Govt. Fees*", period: "project", features: ["Everything in Starter", "IEC modification support where needed", "Priority processing and consultation", "Government / statutory fees extra where applicable*"], description: "Importer Exporter Code application and related export setup support. Final costs depend on the scope and current DGFT requirements.", buttonText: "Get Started", href: "#", isPopular: true },
    { name: "Enterprise", price: "6999 + Govt. Fees*", period: "project", features: ["Everything in Pro", "AD code/export setup coordination", "Export-promotion advisory", "Dedicated expert support", "Government / statutory fees extra where applicable*"], description: "Importer Exporter Code application and related export setup support. Final costs depend on the scope and current DGFT requirements.", buttonText: "Contact Sales", href: "#", isPopular: false },
  ],

  // ISO Registration — Vakilsearch advertises starting prices from ₹1,499; higher tiers are TaxWiseIndia benchmark suggestions. Verify certification-body/accreditation inclusions.
  'iso-registration': [
    { name: "Starter", price: "1499 + Govt. Fees*", period: "project", features: ["Initial ISO certification guidance", "Basic document checklist", "Certification-scope discussion", "Government / statutory fees extra where applicable*"], description: "ISO certification preparation and documentation support. Audit and certification-body fees may be separate depending on standard and provider.", buttonText: "Get Started", href: "#", isPopular: false },
    { name: "Pro", price: "6999 + Govt. Fees*", period: "project", features: ["ISO 9001 or selected-standard documentation support", "Audit preparation guidance", "Priority support", "Government / statutory fees extra where applicable*"], description: "ISO certification preparation and documentation support. Audit and certification-body fees may be separate depending on standard and provider.", buttonText: "Get Started", href: "#", isPopular: true },
    { name: "Enterprise", price: "14999 + Govt. Fees*", period: "project", features: ["Multiple-standard coordination (subject to scope)", "Internal audit/documentation support", "Dedicated consultant", "Government / statutory fees extra where applicable*"], description: "ISO certification preparation and documentation support. Audit and certification-body fees may be separate depending on standard and provider.", buttonText: "Contact Sales", href: "#", isPopular: false },
  ],

  // Professional Tax — TaxWiseIndia suggested benchmark prices; Vakilsearch current fixed website fee was not verified. State statutory tax is separate.
  'professional-tax': [
    { name: "Starter", price: "1999 + Govt. Fees*", period: "project", features: ["Professional Tax registration assistance", "State-specific document checklist", "Basic filing guidance", "Government / statutory fees extra where applicable*"], description: "Professional Tax registration and compliance assistance. State-specific tax liabilities and government charges vary by jurisdiction.", buttonText: "Get Started", href: "#", isPopular: false },
    { name: "Pro", price: "3999 + Govt. Fees*", period: "project", features: ["Everything in Starter", "First applicable return support", "Priority processing", "Government / statutory fees extra where applicable*"], description: "Professional Tax registration and compliance assistance. State-specific tax liabilities and government charges vary by jurisdiction.", buttonText: "Get Started", href: "#", isPopular: true },
    { name: "Enterprise", price: "7999 + Govt. Fees*", period: "year", features: ["Everything in Pro", "Ongoing/annual return coordination", "Notice and compliance support", "Dedicated accountant", "Government / statutory fees extra where applicable*"], description: "Professional Tax registration and compliance assistance. State-specific tax liabilities and government charges vary by jurisdiction.", buttonText: "Contact Sales", href: "#", isPopular: false },
  ],

  // Shop & Establishment — TaxWiseIndia suggested benchmark prices; current fixed Vakilsearch website price was not verified. State/local charges may apply.
  'shop-and-establishment': [
    { name: "Starter", price: "1999 + Govt. Fees*", period: "project", features: ["State-specific registration assistance", "Documentation checklist", "Application status support", "Government / statutory fees extra where applicable*"], description: "Shop and Establishment registration and related compliance guidance based on location and business type.", buttonText: "Get Started", href: "#", isPopular: false },
    { name: "Pro", price: "3999 + Govt. Fees*", period: "project", features: ["Everything in Starter", "Labour-law compliance guidance", "Priority processing", "Government / statutory fees extra where applicable*"], description: "Shop and Establishment registration and related compliance guidance based on location and business type.", buttonText: "Get Started", href: "#", isPopular: true },
    { name: "Enterprise", price: "7999 + Govt. Fees*", period: "year", features: ["Everything in Pro", "Multi-location/state coordination where applicable", "Renewal/compliance tracking", "Dedicated expert", "Government / statutory fees extra where applicable*"], description: "Shop and Establishment registration and related compliance guidance based on location and business type.", buttonText: "Contact Sales", href: "#", isPopular: false },
  ],

  // Digital Signature Certificate — Vakilsearch publishes ₹1,999 standalone DSC and a ₹24,999 business-compliance bundle; middle tier is a TaxWiseIndia benchmark suggestion.
  'digital-signature': [
    { name: "Starter", price: "1999 + Govt. Fees*", period: "project", features: ["DSC package advertised for two-year validity", "Certificate/application assistance", "Document signing support", "Government / statutory fees extra where applicable*"], description: "Digital signature certificate assistance. The ₹24,999 option is a wider compliance bundle, not a standalone DSC price; identity/issuer requirements apply.", buttonText: "Get Started", href: "#", isPopular: false },
    { name: "Pro", price: "4999 + Govt. Fees*", period: "project", features: ["Expanded DSC support and issuance coordination", "Sign/encrypt needs review", "Priority issuance coordination", "Government / statutory fees extra where applicable*"], description: "Digital signature certificate assistance. The ₹24,999 option is a wider compliance bundle, not a standalone DSC price; identity/issuer requirements apply.", buttonText: "Get Started", href: "#", isPopular: true },
    { name: "Enterprise", price: "24999 + Govt. Fees*", period: "project", features: ["Published DSC + business-compliance/GST bundle", "Auditor appointment and company filings", "DIR-3 KYC support for 2 directors", "Bookkeeping/financial statements within package limits", "Government / statutory fees extra where applicable*"], description: "Digital signature certificate assistance. The ₹24,999 option is a wider compliance bundle, not a standalone DSC price; identity/issuer requirements apply.", buttonText: "Contact Sales", href: "#", isPopular: false },
  ],

  // Accounting — Vakilsearch accounting service advertises packages starting at ₹7,999; higher tiers are TaxWiseIndia benchmark suggestions.
  'accounting': [
    { name: "Starter", price: "7999 + Govt. Fees*", period: "month", features: ["Accounting support starting package", "Transaction recording and ledger maintenance", "Basic reports", "Government / statutory fees extra where applicable*"], description: "Accounting and reporting service. Final professional fee depends on transaction volume, turnover, software and reporting scope.", buttonText: "Get Started", href: "#", isPopular: false },
    { name: "Pro", price: "14999 + Govt. Fees*", period: "month", features: ["Everything in Starter", "Monthly P&L and balance sheet", "Bank reconciliation", "Management reporting", "Government / statutory fees extra where applicable*"], description: "Accounting and reporting service. Final professional fee depends on transaction volume, turnover, software and reporting scope.", buttonText: "Get Started", href: "#", isPopular: true },
    { name: "Enterprise", price: "29999 + Govt. Fees*", period: "month", features: ["Everything in Pro", "Higher transaction/turnover scope", "Custom financial reports", "Virtual CFO-style support subject to scope", "Government / statutory fees extra where applicable*"], description: "Accounting and reporting service. Final professional fee depends on transaction volume, turnover, software and reporting scope.", buttonText: "Contact Sales", href: "#", isPopular: false },
  ],

  // Bookkeeping — TaxWiseIndia suggested standalone bookkeeping benchmarks; Vakilsearch publishes bookkeeping within accounting/compliance bundles rather than a verified standalone tier table.
  'bookkeeping': [
    { name: "Starter", price: "1999 + Govt. Fees*", period: "month", features: ["Transaction recording", "Expense tracking", "Basic ledger upkeep", "Government / statutory fees extra where applicable*"], description: "Bookkeeping and financial record maintenance, with transaction-volume limits and reporting depth selected to fit the business.", buttonText: "Get Started", href: "#", isPopular: false },
    { name: "Pro", price: "4999 + Govt. Fees*", period: "month", features: ["Everything in Starter", "Accounts payable/receivable tracking", "Monthly summaries", "Bank reconciliation", "Government / statutory fees extra where applicable*"], description: "Bookkeeping and financial record maintenance, with transaction-volume limits and reporting depth selected to fit the business.", buttonText: "Get Started", href: "#", isPopular: true },
    { name: "Enterprise", price: "9999 + Govt. Fees*", period: "month", features: ["Everything in Pro", "Higher transaction volume", "Financial statement support", "Dedicated bookkeeper/account review", "Government / statutory fees extra where applicable*"], description: "Bookkeeping and financial record maintenance, with transaction-volume limits and reporting depth selected to fit the business.", buttonText: "Contact Sales", href: "#", isPopular: false },
  ],

  // Payroll — TaxWiseIndia suggested benchmark prices; no fixed Vakilsearch payroll package price was verified.
  'payroll': [
    { name: "Starter", price: "2999 + Govt. Fees*", period: "month", features: ["Payroll processing for up to 10 employees", "Salary slip generation", "Basic payroll support", "Government / statutory fees extra where applicable*"], description: "Monthly payroll administration. Employee count, pay structure and statutory compliance scope determine final fees.", buttonText: "Get Started", href: "#", isPopular: false },
    { name: "Pro", price: "6999 + Govt. Fees*", period: "month", features: ["Everything in Starter", "Payroll for up to 50 employees", "TDS/deduction calculations", "Priority support", "Government / statutory fees extra where applicable*"], description: "Monthly payroll administration. Employee count, pay structure and statutory compliance scope determine final fees.", buttonText: "Get Started", href: "#", isPopular: true },
    { name: "Enterprise", price: "12999 + Govt. Fees*", period: "month", features: ["Everything in Pro", "Larger workforce processing", "Statutory deduction coordination", "Dedicated payroll manager", "Government / statutory fees extra where applicable*"], description: "Monthly payroll administration. Employee count, pay structure and statutory compliance scope determine final fees.", buttonText: "Contact Sales", href: "#", isPopular: false },
  ],

  // Provident Fund (PF) — TaxWiseIndia suggested benchmark prices; Vakilsearch did not publish a fixed standalone PF professional fee.
  'pf': [
    { name: "Starter", price: "1999 + Govt. Fees*", period: "month", features: ["PF registration/process assistance", "Monthly challan/document checklist", "Basic compliance support", "Government / statutory fees extra where applicable*"], description: "Provident Fund registration and compliance assistance. Statutory contributions and late charges are additional and separate from service fees.", buttonText: "Get Started", href: "#", isPopular: false },
    { name: "Pro", price: "4999 + Govt. Fees*", period: "month", features: ["Everything in Starter", "Employee add/remove coordination", "Return/compliance support", "Priority assistance", "Government / statutory fees extra where applicable*"], description: "Provident Fund registration and compliance assistance. Statutory contributions and late charges are additional and separate from service fees.", buttonText: "Get Started", href: "#", isPopular: true },
    { name: "Enterprise", price: "9999 + Govt. Fees*", period: "month", features: ["Everything in Pro", "Claim/notice support subject to scope", "Ongoing PF compliance coordination", "Dedicated expert", "Government / statutory fees extra where applicable*"], description: "Provident Fund registration and compliance assistance. Statutory contributions and late charges are additional and separate from service fees.", buttonText: "Contact Sales", href: "#", isPopular: false },
  ],

  // Employee State Insurance (ESI) — Vakilsearch publishes indicative costs around ₹1,950 professional fee and packages around ₹5,999; exact scope and DSC cost require confirmation.
  'esi': [
    { name: "Starter", price: "1950 + Govt. Fees*", period: "project", features: ["ESI registration assistance", "Employer/employee document checklist", "Portal process guidance", "Government / statutory fees extra where applicable*"], description: "ESI registration and employer compliance assistance. Published numbers are indicative; DSC, statutory contributions and other costs may be extra.", buttonText: "Get Started", href: "#", isPopular: false },
    { name: "Pro", price: "5999 + Govt. Fees*", period: "project", features: ["Everything in Starter", "Employee enrolment support", "Compliance/return guidance", "Government / statutory fees extra where applicable*"], description: "ESI registration and employer compliance assistance. Published numbers are indicative; DSC, statutory contributions and other costs may be extra.", buttonText: "Get Started", href: "#", isPopular: true },
    { name: "Enterprise", price: "9999 + Govt. Fees*", period: "project", features: ["Everything in Pro", "Expanded workforce/ongoing support", "Notice/incident reporting guidance subject to scope", "Dedicated expert", "Government / statutory fees extra where applicable*"], description: "ESI registration and employer compliance assistance. Published numbers are indicative; DSC, statutory contributions and other costs may be extra.", buttonText: "Contact Sales", href: "#", isPopular: false },
  ],

  // Financial Statements — TaxWiseIndia suggested stand-alone benchmark prices; Vakilsearch financial statements are included in broader accounting/compliance packages, but separate fixed pricing was not verified.
  'financial-statements': [
    { name: "Starter", price: "3999 + Govt. Fees*", period: "project", features: ["Profit & Loss and balance sheet preparation", "Basic review", "Document checklist", "Government / statutory fees extra where applicable*"], description: "Preparation support for financial statements. Audit, certification and complex consolidated reporting may need separate professional engagement.", buttonText: "Get Started", href: "#", isPopular: false },
    { name: "Pro", price: "8999 + Govt. Fees*", period: "project", features: ["Everything in Starter", "Cash-flow statement", "Notes to accounts", "Consultation", "Government / statutory fees extra where applicable*"], description: "Preparation support for financial statements. Audit, certification and complex consolidated reporting may need separate professional engagement.", buttonText: "Get Started", href: "#", isPopular: true },
    { name: "Enterprise", price: "19999 + Govt. Fees*", period: "project", features: ["Everything in Pro", "Consolidated/complex statement coordination", "Audit assistance where agreed", "Dedicated CA/accounting support", "Government / statutory fees extra where applicable*"], description: "Preparation support for financial statements. Audit, certification and complex consolidated reporting may need separate professional engagement.", buttonText: "Contact Sales", href: "#", isPopular: false },
  ],

  // Legal Consultation — Vakilsearch lists ₹399 for a 30-minute consultation, an introductory offer and per-minute options; extended and retainer prices are TaxWiseIndia suggestions.
  'legal-consultation': [
    { name: "Starter", price: "399 + Govt. Fees*", period: "project", features: ["Published 30-minute legal consultation option", "Initial issue assessment", "General legal guidance", "Government / statutory fees extra where applicable*"], description: "Online consultation with a lawyer/legal expert. Drafting, filing, document review and representation are separate unless specifically included.", buttonText: "Get Started", href: "#", isPopular: false },
    { name: "Pro", price: "999 + Govt. Fees*", period: "project", features: ["Suggested extended consultation package", "Longer consultation and follow-up Q&A", "Written summary where agreed", "Government / statutory fees extra where applicable*"], description: "Online consultation with a lawyer/legal expert. Drafting, filing, document review and representation are separate unless specifically included.", buttonText: "Get Started", href: "#", isPopular: true },
    { name: "Enterprise", price: "9999 + Govt. Fees*", period: "month", features: ["Suggested monthly legal-support retainer", "Routine consultations", "Contract review allowance subject to scope", "Government / statutory fees extra where applicable*"], description: "Online consultation with a lawyer/legal expert. Drafting, filing, document review and representation are separate unless specifically included.", buttonText: "Contact Sales", href: "#", isPopular: false },
  ],

  // Legal Agreements — TaxWiseIndia suggested benchmark prices; Vakilsearch provides templates but a fixed bespoke-drafting price was not publicly verified.
  'legal-agreements': [
    { name: "Starter", price: "1999 + Govt. Fees*", period: "project", features: ["Standard agreement/template assistance", "One round of details/edits", "Basic support", "Government / statutory fees extra where applicable*"], description: "Legal agreement templates and custom drafting support. Bespoke drafting/revisions should be scoped before the final quote.", buttonText: "Get Started", href: "#", isPopular: false },
    { name: "Pro", price: "4999 + Govt. Fees*", period: "project", features: ["Custom agreement drafting for defined scope", "Multiple edits within agreed limit", "Consultation", "Government / statutory fees extra where applicable*"], description: "Legal agreement templates and custom drafting support. Bespoke drafting/revisions should be scoped before the final quote.", buttonText: "Get Started", href: "#", isPopular: true },
    { name: "Enterprise", price: "9999 + Govt. Fees*", period: "project", features: ["Complex/multi-party agreement drafting", "Expanded revisions and negotiation support", "Dedicated legal professional subject to engagement", "Government / statutory fees extra where applicable*"], description: "Legal agreement templates and custom drafting support. Bespoke drafting/revisions should be scoped before the final quote.", buttonText: "Contact Sales", href: "#", isPopular: false },
  ],

  // Business Contracts — TaxWiseIndia suggested benchmark prices; Vakilsearch documents catalogue lists agreement types but no fixed custom-contract package price was verified.
  'business-contracts': [
    { name: "Starter", price: "2499 + Govt. Fees*", period: "project", features: ["NDA/vendor or basic business agreement", "Standard terms review", "Basic support", "Government / statutory fees extra where applicable*"], description: "Drafting support for NDAs, vendor agreements, shareholder agreements, MOUs and other business contracts. Final pricing depends on complexity and revisions.", buttonText: "Get Started", href: "#", isPopular: false },
    { name: "Pro", price: "5999 + Govt. Fees*", period: "project", features: ["Custom commercial/partnership contract", "Consultation and defined revision rounds", "Negotiation support subject to scope", "Government / statutory fees extra where applicable*"], description: "Drafting support for NDAs, vendor agreements, shareholder agreements, MOUs and other business contracts. Final pricing depends on complexity and revisions.", buttonText: "Get Started", href: "#", isPopular: true },
    { name: "Enterprise", price: "14999 + Govt. Fees*", period: "project", features: ["Complex multi-party/shareholder/JV contract", "Expanded review and drafting", "Dedicated counsel subject to engagement", "Government / statutory fees extra where applicable*"], description: "Drafting support for NDAs, vendor agreements, shareholder agreements, MOUs and other business contracts. Final pricing depends on complexity and revisions.", buttonText: "Contact Sales", href: "#", isPopular: false },
  ],

  // Legal Notices — Vakilsearch states a general ₹1,499–₹2,499 range for sending/replying to a legal notice; higher tier is a TaxWiseIndia benchmark suggestion.
  'notices': [
    { name: "Starter", price: "1499 + Govt. Fees*", period: "project", features: ["Legal notice drafting or reply for a standard matter", "Initial information review", "Standard delivery/support subject to terms", "Government / statutory fees extra where applicable*"], description: "Legal notice drafting or replying support. Final professional fee depends on complexity, delivery needs and the lawyer’s scope; statutory/court fees, if any, are additional.", buttonText: "Get Started", href: "#", isPopular: false },
    { name: "Pro", price: "2499 + Govt. Fees*", period: "project", features: ["Higher-complexity notice or reply", "Lawyer review and revisions", "Case-specific consultation", "Government / statutory fees extra where applicable*"], description: "Legal notice drafting or replying support. Final professional fee depends on complexity, delivery needs and the lawyer’s scope; statutory/court fees, if any, are additional.", buttonText: "Get Started", href: "#", isPopular: true },
    { name: "Enterprise", price: "7999 + Govt. Fees*", period: "project", features: ["Complex dispute notice/reply strategy", "Additional document review", "Dedicated legal support subject to written scope", "Government / statutory fees extra where applicable*"], description: "Legal notice drafting or replying support. Final professional fee depends on complexity, delivery needs and the lawyer’s scope; statutory/court fees, if any, are additional.", buttonText: "Contact Sales", href: "#", isPopular: false },
  ],

  // Legal Documentation — TaxWiseIndia suggested benchmark prices; Vakilsearch document library offers templates but custom drafting prices were not publicly listed.
  'legal-documentation': [
    { name: "Starter", price: "499 + Govt. Fees*", period: "project", features: ["Ready-to-use legal document/template assistance", "Basic detail customisation", "Downloadable document support", "Government / statutory fees extra where applicable*"], description: "Templates and tailored legal-document preparation. Notarisation, stamp duty, registration and custom legal review may incur additional charges.", buttonText: "Get Started", href: "#", isPopular: false },
    { name: "Pro", price: "1999 + Govt. Fees*", period: "project", features: ["Customised affidavit, POA or business document", "Document review and defined revisions", "Notarisation guidance where needed", "Government / statutory fees extra where applicable*"], description: "Templates and tailored legal-document preparation. Notarisation, stamp duty, registration and custom legal review may incur additional charges.", buttonText: "Get Started", href: "#", isPopular: true },
    { name: "Enterprise", price: "4999 + Govt. Fees*", period: "project", features: ["Complex legal documentation package", "Registration/documentation coordination", "Dedicated expert support subject to scope", "Government / statutory fees extra where applicable*"], description: "Templates and tailored legal-document preparation. Notarisation, stamp duty, registration and custom legal review may incur additional charges.", buttonText: "Contact Sales", href: "#", isPopular: false },
  ],

};
